#!/usr/bin/env python3
"""Write the release changelog from conventional commit subjects.

    python3 scripts/gen_changelog.py                  # since the last tag
    python3 scripts/gen_changelog.py --since v0.1.0
    python3 scripts/gen_changelog.py --out CHANGELOG.md

Why this exists rather than a committed CHANGELOG.md
----------------------------------------------------
GoReleaser builds a changelog from conventional commits and puts it in
the release body. That is the right mechanism, and duplicating it into a
file that lives in the repository creates a second source of truth which
will disagree with the commits at some point and then be believed.

The gap in GoReleaser's version alone is that the changelog is only
rendered at publish time. `goreleaser check` does not evaluate the
template, and `--snapshot` does not either, so a typo in a group regexp
produces a release with no notes rather than a red build -- and the
moment it is discovered is while the release is being cut. Generating the
same content here, from the same rules, means it can be read and reviewed
before any tag exists.

The grouping rules are duplicated from .goreleaser.yml, which is the
unavoidable cost of this approach. `--check-goreleaser` below is what
keeps the two from drifting: it re-reads .goreleaser.yml and fails if the
filters or group titles here no longer match.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GORELASER = ROOT / ".goreleaser.yml"

# Mirrors .goreleaser.yml `changelog:`. Keep the two in step --
# --check-goreleaser enforces it.
EXCLUDE = ("^docs:", "^test:", "^chore:")

GROUPS = [
    ("Security", 0, r"^.*?(security|vuln|CVE-\d+).*$"),
    ("Features", 1, r"^.*?feat(\(.*?\))?!?:.*$"),
    ("Fixes", 2, r"^.*?fix(\(.*?\))?!?:.*$"),
    ("Other", 999, r"^.*$"),
]


def git(*args: str) -> str:
    r = subprocess.run(
        ["git", *args], capture_output=True, text=True, cwd=ROOT, timeout=60
    )
    if r.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)}: {r.stderr.strip()}")
    return r.stdout


def last_tag() -> str | None:
    r = subprocess.run(
        ["git", "describe", "--tags", "--abbrev=0"],
        capture_output=True, text=True, cwd=ROOT, timeout=60,
    )
    if r.returncode != 0:
        return None
    return r.stdout.strip() or None


def commit_subjects(since: str | None) -> list[str]:
    rng = f"{since}..HEAD" if since else "HEAD"
    out = git("log", "--no-merges", "--format=%s", rng)
    return [ln for ln in out.split("\n") if ln.strip()]


def classify(subjects: list[str]) -> dict[str, list[str]]:
    buckets: dict[str, list[str]] = {t: [] for t, _, _ in GROUPS}
    for s in subjects:
        if any(re.match(p, s) for p in EXCLUDE):
            continue
        for title, _, rx in GROUPS:
            if re.search(rx, s):
                buckets[title].append(s)
                break
    return buckets


def render(subject_since: str | None, subjects: list[str]) -> str:
    tag = subject_since or "the beginning"
    buckets = classify(subjects)
    out = [
        f"# Changelog",
        "",
        f"Generated by `scripts/gen_changelog.py` from commits since "
        f"`{tag}`. Not maintained by hand -- the source of truth is the "
        f"commit log.",
        "",
    ]
    if not subjects:
        out += ["No commits yet.", ""]
        return "\n".join(out)
    for title, order, _ in sorted(GROUPS, key=lambda g: g[1]):
        items = buckets[title]
        if not items:
            continue
        out.append(f"## {title}")
        out.append("")
        for s in items:
            out.append(f"- {s}")
        out.append("")
    return "\n".join(out)


def check_goreleaser() -> list[str]:
    """Fail if this script and .goreleaser.yml have drifted apart."""
    if not GORELASER.exists():
        return [f"missing {GORELASER.name}"]
    text = GORELASER.read_text()
    problems = []
    for pat in EXCLUDE:
        if pat not in text:
            problems.append(
                f"{GORELASER.name} no longer excludes {pat!r}; update "
                f"EXCLUDE in {Path(__file__).name} or the two will disagree"
            )
    for title, _, rx in GROUPS:
        if title == "Other":
            continue
        if f"title: {title}" not in text:
            problems.append(
                f"{GORELASER.name} no longer has a {title!r} group"
            )
    # The regexes themselves, so a changed pattern is caught.
    for _, _, rx in GROUPS:
        if rx not in text:
            problems.append(
                f"{GORELASER.name} no longer contains the regexp {rx!r}"
            )
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--since")
    ap.add_argument("--out")
    ap.add_argument("--check-goreleaser", action="store_true")
    ap.add_argument("--breaking", help="path to a markdown file whose "
                    "contents lead the changelog, before any feature group")
    ap.add_argument("--require-breaking", help="fail unless the rendered "
                    "changelog leads with this file's first heading")
    args = ap.parse_args()

    if args.check_goreleaser:
        problems = check_goreleaser()
        if problems:
            print("changelog rules have drifted from .goreleaser.yml:",
                  file=sys.stderr)
            for p in problems:
                print("  -", p, file=sys.stderr)
            return 1
        print("changelog rules match .goreleaser.yml")
        return 0

    since = args.since or last_tag()
    subjects = commit_subjects(since)
    body = render(since, subjects)

    if args.breaking:
        # Prepended, not appended. The breaking change in this release is the
        # one thing that can silently break a downstream consumer who never
        # reads the feature list, so it is not allowed to compete with it.
        lead = Path(args.breaking).read_text().rstrip() + "\n\n"
        # After the "# Changelog" heading and any version line, so the
        # document still reads as a changelog.
        lines = body.split("\n")
        cut = 0
        for i, line in enumerate(lines):
            if line.startswith("#"):
                cut = i + 1
                break
        if cut and not lines[cut].startswith("\n"):
            cut += 1
        body = "\n".join(lines[:cut]) + "\n" + lead + "\n".join(lines[cut:]).lstrip("\n")

    if args.require_breaking:
        # The breaking change is the one thing in a release that can break a
        # consumer silently, so it may not be left to whoever remembers to
        # pass --breaking. This asserts the rendered output actually leads
        # with it.
        want = Path(args.require_breaking).read_text().strip().split("\n")[0].strip()
        head = body[:len(body) + 1].split("\n")
        seen = [ln.strip() for ln in head[:12]]
        if want not in seen:
            print(f"the changelog does not lead with {want!r}; "
                  f"pass --breaking so it comes first", file=sys.stderr)
            return 1
        print(f"changelog leads with the breaking change: {want}")

    if args.out:
        Path(args.out).write_text(body)
        print(f"wrote {args.out} ({len(subjects)} commit(s) since "
              f"{since or 'the beginning'})")
    else:
        sys.stdout.write(body)
    return 0


if __name__ == "__main__":
    sys.exit(main())
