package sbom

import (
	"encoding/json"
	"strings"

	"github.com/0xsan7/scram/internal/model"
)

// SPDX 2.3 JSON, per the specification's "Annex F: JSON serialization".
// As with CycloneDX, this is a hand-rolled subset of the required fields.

type spdxDoc struct {
	SPDXVersion       string           `json:"spdxVersion"`
	DataLicense       string           `json:"dataLicense"`
	SPDXID            string           `json:"SPDXID"`
	Name              string           `json:"name"`
	DocumentNamespace string           `json:"documentNamespace"`
	CreationInfo      spdxCreationInfo `json:"creationInfo"`
	Packages          []spdxPackage    `json:"packages"`
	Relationships     []spdxRelation   `json:"relationships,omitempty"`
}

type spdxCreationInfo struct {
	Created  string   `json:"created"`
	Creators []string `json:"creators"`
	Comment  string   `json:"comment,omitempty"`
}

type spdxPackage struct {
	SPDXID           string            `json:"SPDXID"`
	Name             string            `json:"name"`
	VersionInfo      string            `json:"versionInfo"`
	DownloadLocation string            `json:"downloadLocation"`
	FilesAnalyzed    bool              `json:"filesAnalyzed"`
	LicenseConcluded string            `json:"licenseConcluded"`
	LicenseDeclared  string            `json:"licenseDeclared"`
	CopyrightText    string            `json:"copyrightText"`
	Checksums        []spdxChecksum    `json:"checksums,omitempty"`
	ExternalRefs     []spdxExternalRef `json:"externalRefs,omitempty"`
	Comment          string            `json:"comment,omitempty"`
}

type spdxChecksum struct {
	Algorithm     string `json:"algorithm"`
	ChecksumValue string `json:"checksumValue"`
}

type spdxExternalRef struct {
	ReferenceCategory string `json:"referenceCategory"`
	ReferenceType     string `json:"referenceType"`
	ReferenceLocator  string `json:"referenceLocator"`
}

type spdxRelation struct {
	SPDXElementID      string `json:"spdxElementId"`
	RelationshipType   string `json:"relationshipType"`
	RelatedSPDXElement string `json:"relatedSpdxElement"`
}

func marshalSPDX(repoName string, comps []model.Component) ([]byte, error) {
	ts := Timestamp().Format("2006-01-02T15:04:05Z")

	doc := spdxDoc{
		SPDXVersion:       SPDXVersion,
		DataLicense:       "CC0-1.0",
		SPDXID:            "SPDXRef-DOCUMENT",
		Name:              repoName,
		DocumentNamespace: spdxNamespace(repoName),
		CreationInfo: spdxCreationInfo{
			Created:  ts,
			Creators: []string{"Tool: " + ToolName + "-" + ToolVersion},
			Comment:  "Generated by SCRAM from lockfiles; no source packages were downloaded",
		},
		Packages: []spdxPackage{},
	}

	for i, c := range comps {
		p := spdxPackage{
			// SPDXIDs may only contain letters, digits, "." and "-", so the
			// PURL is sanitized and indexed to stay unique.
			SPDXID:           spdxID(c.Purl, i),
			Name:             c.Name,
			VersionInfo:      c.Version,
			DownloadLocation: "NOASSERTION",
			FilesAnalyzed:    false,
			LicenseConcluded: "NOASSERTION",
			LicenseDeclared:  spdxLicense(c.License),
			CopyrightText:    "NOASSERTION",
			Comment:          "scram:direct=" + boolStr(c.Direct) + " scram:ecosystem=" + c.Ecosystem,
			ExternalRefs: []spdxExternalRef{{
				ReferenceCategory: "PACKAGE-MANAGER",
				ReferenceType:     "purl",
				ReferenceLocator:  c.Purl,
			}},
		}
		// SHA256 is the only checksum algorithm SPDX 2.3 accepts, so every
		// component gets the identity hash; other algorithms are noted in
		// the comment rather than emitted as invalid entries.
		p.Checksums = []spdxChecksum{{
			Algorithm:     "SHA256",
			ChecksumValue: contentHash(c),
		}}
		doc.Packages = append(doc.Packages, p)

		// DESCRIBES relation: the root document describes each package.
		doc.Relationships = append(doc.Relationships, spdxRelation{
			SPDXElementID:      "SPDXRef-DOCUMENT",
			RelationshipType:   "DESCRIBES",
			RelatedSPDXElement: p.SPDXID,
		})
	}

	return json.MarshalIndent(doc, "", "  ")
}

func spdxID(purl string, i int) string {
	var b strings.Builder
	b.WriteString("SPDXRef-Package-")
	for _, r := range purl {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '.', r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	// The index keeps two purls that sanitize identically from colliding.
	return b.String() + "-" + itoa(i)
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	return string(buf[i:])
}

// spdxLicense maps our license strings onto valid SPDX expressions. Anything
// unrecognized becomes NOASSERTION, because SPDX validators reject
// free-text where an expression is expected.
func spdxLicense(l string) string {
	if l == "" {
		return "NOASSERTION"
	}
	l = strings.TrimSpace(l)
	switch strings.ToUpper(l) {
	case "NOASSERTION", "NONE":
		return l
	}
	// A bare SPDX id like "MIT" or "Apache-2.0" is already a valid expression.
	// Anything with spaces/parens is assumed to be a compound expression and
	// passed through, since we can't validate it without the full id list.
	if strings.ContainsAny(l, " ()+") {
		return l
	}
	return l
}
